### ISSUE TITLE
Irrelevant list of ethereum translators

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [scroll-tech/airdrop-data#1]
Looks like this list is taken from 'All-time View' [leaderboard](https://ethereum.org/en/contributing/translation-program/acknowledgements/). This leaderboard isn't up to date for a long time. It also mistakenly contains 4 proofreaders (bayan-tech, FutureTrans01, ACO_GU, lucidtranslations) from translation agencies. Proofreaders are not volunteer contributors, they are just reviewing and approving contributors' translations and get paid for it, so they shouldn't be on that list.

**Comment by UNOFFICIALbgd** [comment]
You should have compiled a list based on [this rating](https://crowdin.com/project/ethereum-org/reports/top-members), excluding accounts with the 'Aco_' prefix.

**Comment by UNOFFICIALbgd** [comment]
@icemelon

**Comment by icemelon** [comment]
@UNOFFICIALbgd Thank you for bringing this to our attention. We've reached out to the ethereum.org team and obtained the latest, corrected list of translators. The translator list is now updated.
