### ISSUE TITLE
Regarding the issue of missing airdrop personnel list

### ISSUE THREAD

**Issue by bookerhuang** [scroll-tech/airdrop-data#2]
Hi Scroll-tech team, I am a member of the team “DVD,” which won third place at the 2023 ETH Hong Kong Hackathon. Our team consists of four members, but only two of us have received the airdrop. Could you please advise if there is a way to submit proof for the remaining two members to receive the airdrop?

Hackathon Project Link: [2023 ETH Hong Kong Hackathon](https://build.bewater.xyz/en/campaigns/mUwy-2023ETH-HongKong-Hackathon/projects/395)

**Comment by LBruyne** [comment]
Me too. The same problem. Can anyone help with this?
My Hackathon Project Link: https://build.bewater.xyz/en/campaigns/mUwy-2023ETH-HongKong-Hackathon/teams/1001

**Comment by LBruyne** [comment]
> Hi Scroll-tech team, I am a member of the team “DVD,” which won third place at the 2023 ETH Hong Kong Hackathon. Our team consists of four members, but only two of us have received the airdrop. Could you please advise if there is a way to submit proof for the remaining two members to receive the airdrop?
> 
> Hackathon Project Link: [2023 ETH Hong Kong Hackathon](https://build.bewater.xyz/en/campaigns/mUwy-2023ETH-HongKong-Hackathon/projects/395)

I have addressed this issue. You can try with your github account. I don't know the mechanism, but it seems either email or github is okay for this claim. Hope everything okay with u.

**Comment by hwanma** [comment]
Hey there, Juan here from the Community team. @bookerhuang I have reviewed your case and have updated the eligibility list adding the missing 2 hackers. Have them try the claim flow next week.

**Comment by bookerhuang** [comment]
> Hey there, Juan here from the Community team. @bookerhuang I have reviewed your case and have updated the eligibility list adding the missing 2 hackers. Have them try the claim flow next week.

Ok, thank you so much

**Comment by bookerhuang** [comment]
> Me too. The same problem. Can anyone help with this? My Hackathon Project Link: https://build.bewater.xyz/en/campaigns/mUwy-2023ETH-HongKong-Hackathon/teams/1001

lol,  @hwanma responded to me, you can try contacting him @LBruyne

**Comment by bookerhuang** [comment]
> Hey there, Juan here from the Community team. @bookerhuang I have reviewed your case and have updated the eligibility list adding the missing 2 hackers. Have them try the claim flow next week.

Sorry, it seems they still aren’t eligible to claim the airdrop. Please check the requirements and let me know if you have questions, thanks.
